spring:
  application:
    name: base-service-redis
  redis:
    database: 0
    sentinel:
      master: mymaster
      #nodes: 192.168.175.128:6379,192.168.175.128:6380,192.168.175.128:6381
      nodes: 172.16.162.96:6370,172.16.162.96:6371,172.16.162.97:6370
    timeout: 5000
    password: 123456
    host: 192.168.175.128
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
server:
  port: 10003
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/,http://peer3:8762/eureka/