spring:
  application:
    name: base-service-redis
  redis:
    database: 0
    sentinel:
      master: mymaster
      nodes: 192.168.216.157:26379,192.168.216.157:26380,192.168.216.157:26381
    timeout: 5000
    password: 123456
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
server:
  port: 10003
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8760/eureka/,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/