server:
  port: 10003
spring:
  application:
    name: base-service-redis
  redis:
    database: 0
    sentinel:
      master: mymaster
      nodes: 172.16.151.102:26379,172.16.151.102:26380,172.16.151.102:26381
    timeout: 5000
    password: 123456
    host: 172.16.151.102
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8760/eureka/,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/