server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8760/eureka/,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
spring:
  application:
    name: base-service-image
logging:
  config: classpath:log4j2.xml

