server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/,http://peer3:8762/eureka/
spring:
  application:
    name: base-service-image
