spring:
  application:
    name: base-service-redis
  redis:
    database: 0
    sentinel:
      master: mymaster
      nodes: 192.168.216.157:26379,192.168.216.158:26380,192.168.216.159:26381
    timeout: 5000
    host: 192.168.216.157
    port: 6379
    password: 123456
server:
  port: 10003
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka/,http://peer2:20000/eureka/,http://peer3:30000/eureka/